class Element {
    constructor(title, shortTitle, protonsCount, isotopes) {
        this.title = title;
        this.shortTitle = shortTitle;
        this.protonsCount = protonsCount;
        this.isotopes = isotopes;
    }
}

class Isotope {
    constructor(neutronsCount, decay = {type: 'unknown', title: 'unknown'}) {
        this.neutronsCount = neutronsCount;
        this.decay = decay;
    }
}

export default [
    new Element('', 'n', 0, [
            new Isotope(1, {type: 'betta', title: 'betta'})
    ]),
    new Element('Водород', 'H', 1, [
        new Isotope(0, {type: 'stable', title: 'stable'}),
        new Isotope(1, {type: 'stable', title: 'stable'}),
        new Isotope(2, {type: 'betta', title: 'betta'}),
        new Isotope(3),
        new Isotope(4),
        new Isotope(5)
    ]),
    new Element('Helium', 'He', 2, [
        new Isotope(1, {type: 'stable', title: 'stable'}),
        new Isotope(2, {type: 'stable', title: 'stable'}),
        new Isotope(3, {type: 'alpha', title: 'alpha'}),
        new Isotope(4, {type: 'betta', title: 'betta'}),
        new Isotope(5),
        new Isotope(6),
        new Isotope(7, {type: 'neutron', title: 'neutron'}),
        new Isotope(8)
    ]),
    new Element('Litium', 'Li', 3, [
        new Isotope(1, {type: 'alpha', title: 'alpha'}),
        new Isotope(2, {type: 'alpha', title: 'alpha'}),
        new Isotope(3, {type: 'stable', title: 'stable'}),
        new Isotope(4, {type: 'stable', title: 'stable'}),
        new Isotope(5, {type: 'betta', title: 'betta'}),
        new Isotope(6),
        new Isotope(7),
        new Isotope(8)
    ]),
    new Element('Берилий', 'Be', 4, [
        new Isotope(1, {type: 'alpha', title: 'alpha'}),
        new Isotope(2),
        new Isotope(3),
        new Isotope(4),
        new Isotope(5, {type: 'stable', title: 'stable'}),
        new Isotope(6, {type: 'betta', title: 'betta'}),
        new Isotope(7),
        new Isotope(8),
        new Isotope(9),
        new Isotope(10)
    ]),
    new Element('Бор', 'B', 5, [
        new Isotope(2, {type: 'alpha', title: 'alpha'}),
        new Isotope(3),
        new Isotope(4, {type: 'alpha', title: 'alpha'}),
        new Isotope(5, {type: 'stable', title: 'stable'}),
        new Isotope(6, {type: 'stable', title: 'stable'}),
        new Isotope(7, {type: 'betta', title: 'betta'}),
        new Isotope(8),
        new Isotope(9),
        new Isotope(10),
        new Isotope(11),
        new Isotope(12),
        new Isotope(13)
    ]),
    new Element('Углерод', 'C', 6, [
        new Isotope(2),
        new Isotope(3),
        new Isotope(4),
        new Isotope(5),
        new Isotope(6, {type: 'stable', title: 'stable'}),
        new Isotope(7, {type: 'stable', title: 'stable'}),
        new Isotope(8, {type: 'betta', title: 'betta'}),
        new Isotope(9, {type: 'betta', title: 'betta'}),
        new Isotope(10),
        new Isotope(11),
        new Isotope(12),
        new Isotope(13)
    ]),
    new Element('Азот', 'N', 7, [
        new Isotope(3, {type: 'alpha', title: 'alpha'}),
        new Isotope(4, {type: 'alpha', title: 'alpha'}),
        new Isotope(5),
        new Isotope(6),
        new Isotope(7, {type: 'stable', title: 'stable'}),
        new Isotope(8, {type: 'stable', title: 'stable'}),
        new Isotope(9, {type: 'betta', title: 'betta'}),
        new Isotope(10),
        new Isotope(11),
        new Isotope(12),
        new Isotope(13),
        new Isotope(14),
        new Isotope(15),
        new Isotope(16),
        new Isotope(17)
    ]),
    new Element('Oxigen', 'O', 8, [
        new Isotope(4),
        new Isotope(5),
        new Isotope(6),
        new Isotope(7),
        new Isotope(8, {type: 'stable', title: 'stable'}),
        new Isotope(9, {type: 'stable', title: 'stable'}),
        new Isotope(10, {type: 'stable', title: 'stable'}),
        new Isotope(11, {type: 'betta', title: 'betta'}),
        new Isotope(12, {type: 'betta', title: 'betta'}),
        new Isotope(13),
        new Isotope(14),
        new Isotope(15),
        new Isotope(16),
        new Isotope(17),
        new Isotope(18)
    ]),
    new Element('Фтор', 'F', 9, [
        new Isotope(5, {type: 'alpha', title: 'alpha'}),
        new Isotope(6, {type: 'alpha', title: 'alpha'}),
        new Isotope(7, {type: 'alpha', title: 'alpha'}),
        new Isotope(8),
        new Isotope(9),
        new Isotope(10, {type: 'stable', title: 'stable'}),
        new Isotope(11, {type: 'betta', title: 'betta'}),
        new Isotope(12, {type: 'betta', title: 'betta'}),
        new Isotope(13),
        new Isotope(14),
        new Isotope(15),
        new Isotope(16),
        new Isotope(17),
        new Isotope(18),
        new Isotope(19),
        new Isotope(20)
    ]),
    new Element('Neon', 'Ne', 10, [
        new Isotope(6),
        new Isotope(7),
        new Isotope(8),
        new Isotope(9),
        new Isotope(10, {type: 'stable', title: 'stable'}),
        new Isotope(11, {type: 'stable', title: 'stable'}),
        new Isotope(12, {type: 'stable', title: 'stable'}),
        new Isotope(13, {type: 'betta', title: 'betta'}),
        new Isotope(14, {type: 'betta', title: 'betta'}),
        new Isotope(15, {type: 'betta', title: 'betta'}),
        new Isotope(16),
        new Isotope(17),
        new Isotope(18),
        new Isotope(19),
        new Isotope(20),
        new Isotope(21),
        new Isotope(22)
    ]),
    new Element('Натрий', 'Na', 11, [
        new Isotope(7, {type: 'alpha', title: 'alpha'}),
        new Isotope(8, {type: 'alpha', title: 'alpha'}),
        new Isotope(9),
        new Isotope(10),
        new Isotope(11),
        new Isotope(12, {type: 'stable', title: 'stable'}),
        new Isotope(13, {type: 'betta', title: 'betta'}),
        new Isotope(14, {type: 'betta', title: 'betta'}),
        new Isotope(15, {type: 'betta', title: 'betta'}),
        new Isotope(16),
        new Isotope(17),
        new Isotope(18),
        new Isotope(19),
        new Isotope(20),
        new Isotope(21),
        new Isotope(22),
        new Isotope(23),
        new Isotope(24)
    ]),
    new Element('Магний', 'Mg', 12, [
        new Isotope(8),
        new Isotope(9),
        new Isotope(10),
        new Isotope(11),
        new Isotope(12, {type: 'stable', title: 'stable'}),
        new Isotope(13, {type: 'stable', title: 'stable'}),
        new Isotope(14, {type: 'stable', title: 'stable'}),
        new Isotope(15, {type: 'betta', title: 'betta'}),
        new Isotope(16, {type: 'betta', title: 'betta'}),
        new Isotope(17, {type: 'betta', title: 'betta'}),
        new Isotope(18),
        new Isotope(19),
        new Isotope(20),
        new Isotope(21),
        new Isotope(22),
        new Isotope(23),
        new Isotope(24),
        new Isotope(25)
    ]),
    new Element('Аллюминий', 'Al', 13, [
        new Isotope(8, {type: 'alpha', title: 'alpha'}),
        new Isotope(9),
        new Isotope(10),
        new Isotope(11),
        new Isotope(12),
        new Isotope(13),
        new Isotope(14, {type: 'stable', title: 'stable'}),
        new Isotope(15, {type: 'betta', title: 'betta'}),
        new Isotope(16, {type: 'betta', title: 'betta'}),
        new Isotope(17, {type: 'betta', title: 'betta'}),
        new Isotope(18),
        new Isotope(19),
        new Isotope(20),
        new Isotope(21),
        new Isotope(22),
        new Isotope(23),
        new Isotope(24),
        new Isotope(25),
        new Isotope(26)
    ]),
    new Element('Silicium', 'Si', 14, [
        new Isotope(8),
        new Isotope(9),
        new Isotope(10),
        new Isotope(11),
        new Isotope(12),
        new Isotope(13),
        new Isotope(14, {type: 'stable', title: 'stable'}),
        new Isotope(15, {type: 'stable', title: 'stable'}),
        new Isotope(16, {type: 'stable', title: 'stable'}),
        new Isotope(17, {type: 'betta', title: 'betta'}),
        new Isotope(18, {type: 'betta', title: 'betta'}),
        new Isotope(19, {type: 'betta', title: 'betta'}),
        new Isotope(20, {type: 'betta', title: 'betta'}),
        new Isotope(21),
        new Isotope(22),
        new Isotope(23),
        new Isotope(24),
        new Isotope(25),
        new Isotope(26)
    ]),
    new Element('Фосфор', 'P', 15, [
        new Isotope(9, {type: 'alpha', title: 'alpha'}),
        new Isotope(10, {type: 'alpha', title: 'alpha'}),
        new Isotope(11),
        new Isotope(12),
        new Isotope(13),
        new Isotope(14),
        new Isotope(15),
        new Isotope(16, {type: 'stable', title: 'stable'}),
        new Isotope(17, {type: 'betta', title: 'betta'}),
        new Isotope(18, {type: 'betta', title: 'betta'}),
        new Isotope(19, {type: 'betta', title: 'betta'}),
        new Isotope(20, {type: 'betta', title: 'betta'}),
        new Isotope(21),
        new Isotope(22),
        new Isotope(23),
        new Isotope(24),
        new Isotope(25),
        new Isotope(26),
        new Isotope(27),
        new Isotope(28),
        new Isotope(29),
        new Isotope(30),
        new Isotope(31),
        new Isotope(32),
        new Isotope(33)
    ]),
];